---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baibiao.
--- DateTime: 2026/1/18 下午6:58
---

-- Redis 中的 key (phone_code:login:130xxxxxxxx)
local key = KEYS[1]
-- 验证次数 key (phone_code:login:130xxxxxxxx:cnt)
local cntKey = key..":cnt"
-- 你的验证码
local val = ARGV[1]
-- 过期时间 （-2 不存在， -1 存在，没有过期时间， 正数 表示过期时间）
local ttl = tonumber(redis.call("ttl", key))
if ttl == -1 then
    -- key 存在，没有过期时间 （手动设置错误，没有给过期时间）
    return -2
elseif ttl == -2 or ttl < 540 then
    -- key 不存在 or 过期时间小于9分钟了（已经过了一分钟了）
    redis.call("set", key, val)
    redis.call("expire", key, 600)
    redis.call("set", cntKey, 3)
    redis.call("expire", cntKey, 600)
    return 0
else
    -- 发送太频繁
    return -1
end

--local key = KEYS[1]
--local cntKey = key..":cnt"
--local val = ARGV[1]
--local ttl = tonumber(redis.call("ttl", key))
--
--if ttl == -1 then
--    return -2
--elseif ttl == -2 or ttl < 540 then
--    -- 因为redis无法调用发送验证码的服务，所以就可以认为把验证码存在redis中，就相当于可以发送验证码了
--    redis.call("set", key, val)
--    redis.call("expire", key, 600)
--    redis.call("set", cntKey, 3)
--    redis.call("expire", cntKey, 600)
--    -- 一切正常
--    return 0
--else
--    return -1
--end