---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baibiao.
--- DateTime: 2026/1/18 下午7:47
---

local key = KEYS[1]
local expectedCode = ARGV[1]
local cntKey = key..":cnt"
local code = redis.call("get", key)
local cnt = tonumber(redis.call("get", cntKey))

if cnt == nil or cnt <= 0 then
    --    用户次数用完
    return -1
elseif expectedCode == code then
    --    用户数对了
    --    用完不能再用了
    redis.call("set", cntKey, -1)
    return 0
else
    --    用户输错了
    redis.call("decr", cntKey)
    return -2
end