---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by baibiao.
--- DateTime: 2026/1/11 上午10:58
---
wrk.method = "GET"
wrk.headers["Content-type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
wrk.headers["Authorization"] = "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgxMDMwMjMsIlVzZXJJZCI6NiwiVXNlckFnZW50IjoiQXBpZm94LzEuMC4wIChodHRwczovL2FwaWZveC5jb20pIn0.Dt2TU81fz26LWlY4FUlniwC8VVshZoHYeUjZjQcSjkDSEhEhKl-mke6MjyGttV1LVDp85mbpANQJTPdvhf6G8w"